version: "3"
services:
  snaxi:
    build:
      context: .
    image: snaxi
    container_name: snaxi
    volumes:
      - ./runtime/static:/app/packages/server/static
    environment:
      - TZ=Asia/Shanghai
    expose:
      - "30054-30054"
    ports:
      - "30054-30054:30054-30054"
    networks:
      - snaxi
networks:
  snaxi:
    driver: bridge